# Generated by Django 2.2.12 on 2020-04-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='comment',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
