# Generated by Django 2.2.12 on 2020-04-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=10, verbose_name='Sort order')),
                ('status', models.BooleanField(default=0, verbose_name='Status')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appnews.Categories', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order'],
            },
        ),
    ]
