[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_counter_contract = "7Kma5Nydhzrei3LAC52Z1eCVPMUbSs91JsuSDzSB3Xs5"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "http://127.0.0.1:8899/"
#wallet = "~/.config/solana/id.json"
cluster = "https://api.devnet.solana.com"
wallet = "./wallet.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
